### ISSUE TITLE
Error in tracking/pose estimation

### ISSUE THREAD

**Issue by mcarone001** [ZexinChen/AlphaTracker#19]
Hi, first of all thank you for all the amazing work you've done. I'm trying to use AlphaTracker via google colab and in step 9 I came across this error:
`Traceback (most recent call last):
  File "./PoseFlow/tracker-general-fixNum-newSelect-noOrb.py", line 375, in <module>
    display_pose_cv2(image_dir, vis_dir, notrack, cmap, args)
  File "./PoseFlow/tracker-general-fixNum-newSelect-noOrb.py", line 46, in display_pose_cv2
    img_tmp = cv2.imread(os.path.join(imgdir,args.image_format%(list(tracked.keys())[0])))
IndexError: list index out of range`
Could you help me out? thank you so much

**Comment by laurelrr** [comment]
Hi,
Thanks for your interest in AlphaTracker!
Could you please verify that there are images in your image directory : /gdrive/result_folder/oriFrameFromVideo//Trial60/frame_folder
and include their file size?

Are you running our sample data or your own data?
Thanks,
Laurel

**Comment by mcarone001** [comment]
Thank you so much for your reply.
Yes I can conferm that there are all the frames. They're all different sizes (ranging approximately from 860 KB to 1,000 KB).
I'm running on your sample data.

**Comment by laurelrr** [comment]
It looks like you are attempting to track a video called "Trial60.avi".  Is this the sample video we provided and you have renamed it or is this one of your own videos?
First, would you be able to see if tracking runs on the sample demo video that we provided.

After you confirm that tracking works correctly on our sample video, you could try to convert from .avi to .mp4 format.

Thank you.
